# Generated by Django 5.0.6 on 2024-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('is_gain', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploaded/')),
            ],
        ),
    ]
