# Generated by Django 5.0.6 on 2024-05-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debit',
            old_name='user',
            new_name='user_id',
        ),
    ]
