# Generated by Django 5.0.6 on 2024-05-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_debit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='is_gain',
            field=models.IntegerField(),
        ),
    ]
