# Generated by Django 5.0.6 on 2024-05-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_debit_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debit',
            old_name='user_id',
            new_name='user',
        ),
    ]
