# Generated by Django 5.0.6 on 2024-05-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_user_id_debit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debit',
            name='user',
        ),
    ]
